### ISSUE TITLE
rpm files need updating

### ISSUE THREAD

**Issue by rkwesk** [epoptes/epoptes#106] opened 2019-11-01 12:03 UTC
I did an install of Fedora 30 but cannot get epoptes because it only had version 0.5 and their psycha wouldn't satisfy - I tried to install epoptes and found that once I installed an rpm called sphere it gave me both epoptes and epoptes-client. However, their versions were 0.5 and so I came aground with psycha.

Searching Fedora packages for in https://pkgs.org/download/epoptes did not list Fedora 31 or epoptes 1.0.

     Running transaction
     Preparing        :                                                            1/1 
     Running scriptlet: epoptes-client-0.5.10-4.1.noarch                           1/1 
     /var/tmp/rpm-tmp.ctsTeR: line 1: fg: no job control
     error: %prein(epoptes-client-0.5.10-4.1.noarch) scriptlet failed, exit status 1

     Error in PREIN scriptlet in rpm package epoptes-client
     Verifying        : epoptes-client-0.5.10-4.1.noarch                           1/1 

      Failed:
     epoptes-client-0.5.10-4.1.noarch

      Problem: conflicting requests
       - nothing provides python-pycha needed by epoptes-0.5.10-4.1.noarch
      =======================================================================
      Package         Architecture   Version              Repository                Size
      =======================================================================
      Skipping packages with broken dependencies:
      epoptes         noarch         0.5.10-4.1           rpmsphere-noarch         258 k

      Transaction Summary
      =======================================================================
      Skip  1 Package

      Nothing to do.

Richard

**Comment by alkisg** [comment] 2019-11-01 12:24
Hi Richard,

as mentioned in the LTSP discussion issues, upstream Epoptes developers do not package Epoptes for RHEL, Fedora etc; we're only using .deb based distributions.

Cyberorg did the initial rpm packaging for OpenSUSE, but I think he's moved to Ubuntu since, so I don't know if any Fedora package maintainer is interested in packaging Epoptes.

So I'm closing this with "WontFix", but if some Epoptes user knows RPM packaging and wants to implement it, just ping. Or if sponsoring is ever found, it changes things.

Discussion can be continued here even if the issue is closed.

**Closed by alkisg** 2019-11-01 12:24 UTC
