### ISSUE TITLE
Client Logon don't allow access server (just on 64 Bits) & Anothers things

### ISSUE THREAD

**Issue by inukaze** [Epoptes/epoptes#62] opened 2018-08-02 15:56 UTC
Hi there, i had this behavior with 64 Bits versions of Epoptes, Epoptes-client and some viewers like xvnc4viewer, ssvnc, etc 

1 - On the 64 Bits machine, when the remote machine is on the Logon Screen, if i try to control it, i can't.
But on the 32 Bits machines, i don't have this problem, i can control without any problem.

On the 32 Bits machine i am using Lubuntu 16.04
On the 64 Bits machine i am using Lubuntu 18.04 

Both uses "xvnc4viewer" (VNC Viewer Free Edition 4.1.1). the another thing is if i try to share server desktop on the 64 Bits machines, don't work neither. but on the 32 Bits machines, works without problems.

But i don't understand why i can control when is on the logon screen on the 64 bits machine, if are using exactly the same versions. 

Which configuration files i must edit for allow control on logon screen ?

2 - Why Viewers are admit to use fine with Epoptes. because i really need one can stretch, the content, the to window. like in VirtualBox when you press Host+C

3 - Features Request - 

A ) Please allow multiples servers i had multiples rooms and i need to control from the support office. for the classes of teachers. (i need control 4 rooms, 3 on floor 1, and 1 in floor 10)

B) Let the user choose the default viewer if detect multiples viewers installed on the system right now i had installed : vinagre, xvnc4viewer, xtightvncviewer, realvncviewer, ssvnc, turbovnc.

Epoptes just use right now ssvnc. i want to try with another without install/reinstall another packages on my system.

C) The user can set as default is want to share server desktop on fullscreen or a window.

**Comment by agrgal** [comment] 2018-09-12 07:47
No an expert at all, but in 64-bits machines this fix worked for me! https://github.com/Epoptes/epoptes/issues/3 . Maybe it's useful for you.
Anyway, the other issue remains: client logon screen is disabled for me.

**Comment by alkisg** [comment] 2018-09-19 17:59
1) This was fixed in the newer Epoptes 1.0.0. I.e. systemd support instead of if-up. See https://github.com/Epoptes/epoptes/issues/65#issuecomment-422896797 for instructions on how to test with Epoptes 1.0.0.
2) ssvnc supports that.
3) (A) Can't be done with the current design. You need to set up a remote connection to the PC where the epoptes daemon runs.
(B) You can set VNCVIEWER in /etc/default/epoptes.
(C) A preferences dialog would be a good idea, yeah.

**Comment by alkisg** [comment] 2018-11-28 08:49
Since the only unimplemented task in this issue is about a preferences dialog, I'll close it because the description of the issue is about other things.

**Closed by alkisg** 2018-11-28 08:49 UTC
