### ISSUE TITLE
Epoptes Zero division error when see screen

### ISSUE THREAD

**Issue by mdenis35** [epoptes/epoptes#180] opened 2022-12-19 11:13 UTC
Hi,

Since i switch to LTSP new version and Ubuntu 22.04, i can't see the screen of the clients in epoptes.
Il can start or shutdown pc-client but not see them.

I specify that i an in thin-fat client and i use liquorix kernel for my clients. Is it the cause ?

This is the error i get as soon as i click on the client to see it in the epoptes console

File "/usr/share/epoptes-client/./thumbshot.py", line 54, in <module>
    main()
  File "/usr/share/epoptes-client/./thumbshot.py", line 45, in main
    sys.stdout.buffer.write(thumbshot(int(sys.argv[1]), int(sys.argv[2])))
  File "/usr/share/epoptes-client/./thumbshot.py", line 26, in thumbshot
    ctx.scale(float(width) / geometry.width, float(height) / geometry.height)
ZeroDivisionError: float division by zero

I precise too that i can't use other kernel than liquorix because i can't boot otherwise

Thanks for your help and merry christmas
Marc

**Comment by alkisg** [comment] 2022-12-19 11:21
Hi @mdenis35, have a look at this discussion, does it solve your issue?

https://github.com/epoptes/epoptes/discussions/176

**Comment by mdenis35** [comment] 2022-12-19 11:28
sorry 

I just saw your message and I tested it is ok.

That's great !

My teachers will be happy. 

One less thorn in the side.

Thank you for your speed and your work Alkis !

Marc

**Comment by alkisg** [comment] 2022-12-19 11:31
@mdenis35 great, I'll close this issue now as it's not a bug in the epoptes code.

(issues are reserved for bugs, while discussions for ...discussions :))

**Closed by alkisg** 2022-12-19 11:31 UTC
