### ISSUE TITLE
Epoptes sometimes erases groups.json

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#83] opened 2018-11-21 07:06 UTC
I don't know exactly when that happens, but sometimes groups.json is written with size=0, and all the groups are lost.

If the bug cannot be pinpointed in the code, maybe it would help to automatically create backups, like ~/.config/epoptes/groups.json.bak.

**Comment by alkisg** [comment] 2018-11-21 11:11
I couldn't reproduce the issue.
I did some related code improvements though, i.e. using "with" when opening files, so that they're [closed properly even when exceptions occur](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files).
So let's consider the issue closed for now, and let's see if it happens again.

Thanks, fix committed in https://github.com/Epoptes/epoptes/commit/d54d5a43f6db2d1a8202ca91bbb0f4491f4281a9.

**Closed by alkisg** 2018-11-21 11:11 UTC
